bundler_args: --without development heroku --path=~/.bundle

language: ruby

rvm:
  - 2.0.0

before_install:
  - ! 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler fog
  - ./script/travis/bundle_install.sh

before_script:
  - cp config/database.travis.yml config/database.yml

after_script:
  - ruby script/travis/bundle_cache.rb

script: bundle exec rake db:create db:migrate; bundle exec xvfb-run rspec

notifications:
  email: false

env:
  global:
    - BUNDLE_ARCHIVE="procure-io-travisbundle"
    - AWS_S3_BUCKET="travisbundlercache"
    - RAILS_ENV=test
    - secure: ! 'fNwCcNewOzck8tHDF8SXjkOhxNP3K9r5OU1ePzxR0012oJvIpNoGvQTfMT1x

        YNEbeV/5qziXLXEA+S+qM+njWouH3Mqwfhaj6y0KJxx4yld+tDz4cJQdnRnu

        MRirO9QJNz5+71XWnuCTkAV+iEB9vqpTlTy7CDtvlN3Q7mz1WpI='
